#
#	Script to insert Connections in the couchdb database for travelcontrol
#
$travelControlUrl="http://127.0.0.1:5984/travelcontrol"

$connections = @(
'{ "DocType": 2, "From":"asdm", "To":"dmn" }'
'{ "DocType": 2, "From":"dmn", "To":"wp" }'
'{ "DocType": 2, "From":"wp", "To":"almm" }'
'{ "DocType": 2, "From":"almm", "To":"alm" }'
'{ "DocType": 2, "From":"alm", "To":"almp" }'
'{ "DocType": 2, "From":"almp", "To":"almb" }'
'{ "DocType": 2, "From":"almb", "To":"lls" }'
'{ "DocType": 2, "From":"laa", "To":"vbl" }'
'{ "DocType": 2, "From":"ldv", "To":"vbl" }'
'{ "DocType": 2, "From":"ldv", "To":"pnk" }'
'{ "DocType": 2, "From":"rdr", "To":"pnk" }'
'{ "DocType": 2, "From":"rdr", "To":"rtwp" }'
'{ "DocType": 2, "From":"rtkw", "To":"rtwp" }'
'{ "DocType": 2, "From":"rtkw", "To":"rtbw" }'
'{ "DocType": 2, "From":"rth", "To":"rtbw" }'
'{ "DocType": 2, "From":"ldv", "To":"ztmv" }'
'{ "DocType": 2, "From":"ztmv", "To":"ztmcw" }'
'{ "DocType": 2, "From":"ztmv", "To":"ztmb" }'
'{ "DocType": 2, "From":"ztmv", "To":"ztmm" }'
'{ "DocType": 2, "From":"ztmm", "To":"dmp" }'
'{ "DocType": 2, "From":"dmp", "To":"dtwa" }'
'{ "DocType": 2, "From":"dtwa", "To":"ztmd" }'
'{ "DocType": 2, "From":"ztmd", "To":"ztmcw" }'
'{ "DocType": 2, "From":"ztmcw", "To":"zsh" }'
'{ "DocType": 2, "From":"zsh", "To":"ztmp" }'
'{ "DocType": 2, "From":"ztmp", "To":"ztms" }'
'{ "DocType": 2, "From":"ztms", "To":"ztml" }'
'{ "DocType": 2, "From":"ztml", "To":"ley" }'
'{ "DocType": 2, "From":"ley", "To":"ztmb" }'
'{ "DocType": 2, "From":"vb", "To":"ztm" }'
'{ "DocType": 2, "From":"vb", "To":"gv" }'
'{ "DocType": 2, "From":"ztm", "To":"ztmo" }'
'{ "DocType": 2, "From":"gd", "To":"ztmo" }'
'{ "DocType": 2, "From":"amf", "To":"bnn" }'
'{ "DocType": 2, "From":"apd", "To":"bnn" }'
'{ "DocType": 2, "From":"bnn", "To":"bnc" }'
'{ "DocType": 2, "From":"ltn", "To":"bnc" }'
'{ "DocType": 2, "From":"ltn", "To":"edc" }'
'{ "DocType": 2, "From":"ed", "To":"edc" }'
'{ "DocType": 2, "From":"apd", "To":"dv" }'
'{ "DocType": 2, "From":"es", "To":"hgl" }'
'{ "DocType": 2, "From":"amf", "To":"amfs" }'
'{ "DocType": 2, "From":"bgn", "To":"rsd" }'
'{ "DocType": 2, "From":"rtb", "To":"rtd" }'
'{ "DocType": 2, "From":"rtd", "To":"sdm" }'
'{ "DocType": 2, "From":"gv", "To":"laa" }'
'{ "DocType": 2, "From":"hfd", "To":"nvp" }'
'{ "DocType": 2, "From":"ledn", "To":"nvp" }'
'{ "DocType": 2, "From":"asdl", "To":"shl" }'
'{ "DocType": 2, "From":"asdl", "To":"asdv" }'
'{ "DocType": 2, "From":"ass", "To":"asdv" }'
'{ "DocType": 2, "From":"asd", "To":"ass" }'
'{ "DocType": 2, "From":"vs", "To":"vss" }'
'{ "DocType": 2, "From":"mdb", "To":"vss" }'
'{ "DocType": 2, "From":"arn", "To":"mdb" }'
'{ "DocType": 2, "From":"arn", "To":"gs" }'
'{ "DocType": 2, "From":"bzl", "To":"gs" }'
'{ "DocType": 2, "From":"bzl", "To":"krg" }'
'{ "DocType": 2, "From":"kbd", "To":"krg" }'
'{ "DocType": 2, "From":"kbd", "To":"rb" }'
'{ "DocType": 2, "From":"bgn", "To":"rb" }'
'{ "DocType": 2, "From":"bd", "To":"tb" }'
'{ "DocType": 2, "From":"ac", "To":"bkl" }'
'{ "DocType": 2, "From":"ac", "To":"asb" }'
'{ "DocType": 2, "From":"utl", "To":"utm" }'
'{ "DocType": 2, "From":"hor", "To":"utm" }'
'{ "DocType": 2, "From":"bkl", "To":"mas" }'
'{ "DocType": 2, "From":"mas", "To":"ut" }'
'{ "DocType": 2, "From":"bnk", "To":"ut" }'
'{ "DocType": 2, "From":"bnk", "To":"db" }'
'{ "DocType": 2, "From":"db", "To":"mrn" }'
'{ "DocType": 2, "From":"mrn", "To":"vndw" }'
'{ "DocType": 2, "From":"vndc", "To":"vndw" }'
'{ "DocType": 2, "From":"rhn", "To":"vndc" }'
'{ "DocType": 2, "From":"ehb", "To":"ehv" }'
'{ "DocType": 2, "From":"bet", "To":"ehb" }'
'{ "DocType": 2, "From":"bet", "To":"btl" }'
'{ "DocType": 2, "From":"btl", "To":"vg" }'
'{ "DocType": 2, "From":"ht", "To":"vg" }'
'{ "DocType": 2, "From":"asn", "To":"gn" }'
'{ "DocType": 2, "From":"zl", "To":"wz" }'
'{ "DocType": 2, "From":"wz", "To":"hde" }'
'{ "DocType": 2, "From":"hde", "To":"ns" }'
'{ "DocType": 2, "From":"ns", "To":"hd" }'
'{ "DocType": 2, "From":"hd", "To":"eml" }'
'{ "DocType": 2, "From":"eml", "To":"pt" }'
'{ "DocType": 2, "From":"pt", "To":"nkk" }'
'{ "DocType": 2, "From":"nkk", "To":"amfs" }'
'{ "DocType": 2, "From":"hgv", "To":"mp" }'
'{ "DocType": 2, "From":"mp", "To":"zl" }'
'{ "DocType": 2, "From":"bl", "To":"hgv" }'
'{ "DocType": 2, "From":"asn", "To":"bl" }'
'{ "DocType": 2, "From":"lls", "To":"zl" }'
'{ "DocType": 2, "From":"asdz", "To":"shl" }'
'{ "DocType": 2, "From":"asa", "To":"asd" }'
'{ "DocType": 2, "From":"ass", "To":"zd" }'
'{ "DocType": 2, "From":"cas", "To":"hlo" }'
'{ "DocType": 2, "From":"amr", "To":"hlo" }'
'{ "DocType": 2, "From":"amr", "To":"amrn" }'
'{ "DocType": 2, "From":"amrn", "To":"hwd" }'
'{ "DocType": 2, "From":"hwd", "To":"sgn" }'
'{ "DocType": 2, "From":"ehv", "To":"gp" }'
'{ "DocType": 2, "From":"gp", "To":"hze" }'
'{ "DocType": 2, "From":"hze", "To":"wt" }'
'{ "DocType": 2, "From":"rm", "To":"wt" }'
'{ "DocType": 2, "From":"asa", "To":"dvd" }'
'{ "DocType": 2, "From":"hdr", "To":"hdrz" }'
'{ "DocType": 2, "From":"ana", "To":"hdrz" }'
'{ "DocType": 2, "From":"ana", "To":"sgn" }'
'{ "DocType": 2, "From":"asa", "To":"asb" }'
'{ "DocType": 2, "From":"asb", "To":"dvd" }'
'{ "DocType": 2, "From":"hn", "To":"hnk" }'
'{ "DocType": 2, "From":"hks", "To":"hnk" }'
'{ "DocType": 2, "From":"bkg", "To":"hks" }'
'{ "DocType": 2, "From":"bkf", "To":"bkg" }'
'{ "DocType": 2, "From":"bkf", "To":"ekz" }'
'{ "DocType": 2, "From":"hn", "To":"obd" }'
'{ "DocType": 2, "From":"hwd", "To":"obd" }'
'{ "DocType": 2, "From":"gv", "To":"gvc" }'
'{ "DocType": 2, "From":"ehv", "To":"hmh" }'
'{ "DocType": 2, "From":"hmh", "To":"hm" }'
'{ "DocType": 2, "From":"hmbh", "To":"hm" }'
'{ "DocType": 2, "From":"dn", "To":"hmbh" }'
'{ "DocType": 2, "From":"dn", "To":"hrt" }'
'{ "DocType": 2, "From":"br", "To":"hrt" }'
'{ "DocType": 2, "From":"br", "To":"vl" }'
'{ "DocType": 2, "From":"had", "To":"hlm" }'
'{ "DocType": 2, "From":"ass", "To":"hlm" }'
'{ "DocType": 2, "From":"ddr", "To":"ddzd" }'
'{ "DocType": 2, "From":"ddzd", "To":"zlw" }'
'{ "DocType": 2, "From":"zlw", "To":"zvb" }'
'{ "DocType": 2, "From":"odb", "To":"zvb" }'
'{ "DocType": 2, "From":"odb", "To":"rsd" }'
'{ "DocType": 2, "From":"cas", "To":"utg" }'
'{ "DocType": 2, "From":"ed", "To":"klp" }'
'{ "DocType": 2, "From":"ah", "To":"est" }'
'{ "DocType": 2, "From":"est", "To":"nm" }'
'{ "DocType": 2, "From":"nm", "To":"nmd" }'
'{ "DocType": 2, "From":"nmd", "To":"wc" }'
'{ "DocType": 2, "From":"wc", "To":"rvs" }'
'{ "DocType": 2, "From":"rvs", "To":"o" }'
'{ "DocType": 2, "From":"o", "To":"ow" }'
'{ "DocType": 2, "From":"ow", "To":"rs" }'
'{ "DocType": 2, "From":"rs", "To":"hto" }'
'{ "DocType": 2, "From":"hto", "To":"ht" }'
'{ "DocType": 2, "From":"nm", "To":"nmh" }'
'{ "DocType": 2, "From":"nmh", "To":"ck" }'
'{ "DocType": 2, "From":"ck", "To":"bmr" }'
'{ "DocType": 2, "From":"bmr", "To":"vlb" }'
'{ "DocType": 2, "From":"vlb", "To":"vry" }'
'{ "DocType": 2, "From":"vry", "To":"br" }'
'{ "DocType": 2, "From":"hn", "To":"pmo" }'
'{ "DocType": 2, "From":"hfd", "To":"shl" }'
'{ "DocType": 2, "From":"zp", "To":"vd" }'
'{ "DocType": 2, "From":"vd", "To":"rl" }'
'{ "DocType": 2, "From":"rl", "To":"ltv" }'
'{ "DocType": 2, "From":"ltv", "To":"ww" }'
'{ "DocType": 2, "From":"dv", "To":"zp" }'
'{ "DocType": 2, "From":"dv", "To":"ost" }'
'{ "DocType": 2, "From":"ost", "To":"wh" }'
'{ "DocType": 2, "From":"wh", "To":"zl" }'
'{ "DocType": 2, "From":"bd", "To":"etn" }'
'{ "DocType": 2, "From":"etn", "To":"rsd" }'
'{ "DocType": 2, "From":"rh", "To":"dr" }'
'{ "DocType": 2, "From":"rh", "To":"ahpr" }'
'{ "DocType": 2, "From":"ahp", "To":"ahpr" }'
'{ "DocType": 2, "From":"ahp", "To":"ah" }'
'{ "DocType": 2, "From":"ahp", "To":"dvn" }'
'{ "DocType": 2, "From":"dvn", "To":"zv" }'
'{ "DocType": 2, "From":"zv", "To":"did" }'
'{ "DocType": 2, "From":"did", "To":"wl" }'
'{ "DocType": 2, "From":"wl", "To":"dtch" }'
'{ "DocType": 2, "From":"dtch", "To":"dtc" }'
'{ "DocType": 2, "From":"dtc", "To":"tbg" }'
'{ "DocType": 2, "From":"tbg", "To":"vsv" }'
'{ "DocType": 2, "From":"vsv", "To":"atn" }'
'{ "DocType": 2, "From":"atn", "To":"ww" }'
'{ "DocType": 2, "From":"bmn", "To":"zp" }'
'{ "DocType": 2, "From":"kbk", "To":"zp" }'
'{ "DocType": 2, "From":"kbk", "To":"apd" }'
'{ "DocType": 2, "From":"dr", "To":"bmn" }'
'{ "DocType": 2, "From":"kbw", "To":"zd" }'
'{ "DocType": 2, "From":"kbw", "To":"kzd" }'
'{ "DocType": 2, "From":"kzd", "To":"wm" }'
'{ "DocType": 2, "From":"kma", "To":"wm" }'
'{ "DocType": 2, "From":"kma", "To":"utg" }'
'{ "DocType": 2, "From":"rtd", "To":"rtn" }'
'{ "DocType": 2, "From":"rta", "To":"rtn" }'
'{ "DocType": 2, "From":"cps", "To":"rta" }'
'{ "DocType": 2, "From":"cps", "To":"nwk" }'
'{ "DocType": 2, "From":"gd", "To":"nwk" }'
'{ "DocType": 2, "From":"gd", "To":"gdg" }'
'{ "DocType": 2, "From":"nwl", "To":"sdm" }'
'{ "DocType": 2, "From":"nwl", "To":"vdo" }'
'{ "DocType": 2, "From":"vdg", "To":"vdo" }'
'{ "DocType": 2, "From":"vdg", "To":"vdw" }'
'{ "DocType": 2, "From":"mss", "To":"vdw" }'
'{ "DocType": 2, "From":"mss", "To":"msw" }'
'{ "DocType": 2, "From":"hld", "To":"msw" }'
'{ "DocType": 2, "From":"hld", "To":"hlds" }'
'{ "DocType": 2, "From":"dmnz", "To":"wp" }'
'{ "DocType": 2, "From":"dmnz", "To":"dvd" }'
'{ "DocType": 2, "From":"dvd", "To":"rai" }'
'{ "DocType": 2, "From":"asdz", "To":"rai" }'
'{ "DocType": 2, "From":"hvs", "To":"hvsp" }'
'{ "DocType": 2, "From":"ut", "To":"uto" }'
'{ "DocType": 2, "From":"hvs", "To":"hvsn" }'
'{ "DocType": 2, "From":"bsmz", "To":"hvsn" }'
'{ "DocType": 2, "From":"bsmz", "To":"ndb" }'
'{ "DocType": 2, "From":"ndb", "To":"wp" }'
'{ "DocType": 2, "From":"dtz", "To":"sdm" }'
'{ "DocType": 2, "From":"dt", "To":"dtz" }'
'{ "DocType": 2, "From":"dt", "To":"rsw" }'
'{ "DocType": 2, "From":"gvmw", "To":"rsw" }'
'{ "DocType": 2, "From":"gv", "To":"gvmw" }'
'{ "DocType": 2, "From":"ddr", "To":"zwd" }'
'{ "DocType": 2, "From":"brd", "To":"zwd" }'
'{ "DocType": 2, "From":"brd", "To":"rlb" }'
'{ "DocType": 2, "From":"rlb", "To":"rtz" }'
'{ "DocType": 2, "From":"rtb", "To":"rtz" }'
'{ "DocType": 2, "From":"bd", "To":"bdpb" }'
'{ "DocType": 2, "From":"bdpb", "To":"zlw" }'
'{ "DocType": 2, "From":"ovn", "To":"zvt" }'
'{ "DocType": 2, "From":"hlm", "To":"ovn" }'
'{ "DocType": 2, "From":"brn", "To":"sd" }'
'{ "DocType": 2, "From":"sd", "To":"st" }'
'{ "DocType": 2, "From":"st", "To":"stz" }'
'{ "DocType": 2, "From":"dld", "To":"stz" }'
'{ "DocType": 2, "From":"bhv", "To":"dld" }'
'{ "DocType": 2, "From":"bhv", "To":"uto" }'
'{ "DocType": 2, "From":"amf", "To":"dld" }'
'{ "DocType": 2, "From":"gvc", "To":"laa" }'
'{ "DocType": 2, "From":"gvm", "To":"laa" }'
'{ "DocType": 2, "From":"gvm", "To":"vst" }'
'{ "DocType": 2, "From":"dvnk", "To":"vst" }'
'{ "DocType": 2, "From":"dvnk", "To":"ledn" }'
'{ "DocType": 2, "From":"ledn", "To":"vh" }'
'{ "DocType": 2, "From":"hil", "To":"vh" }'
'{ "DocType": 2, "From":"had", "To":"hil" }'
'{ "DocType": 2, "From":"lut", "To":"std" }'
'{ "DocType": 2, "From":"bk", "To":"lut" }'
'{ "DocType": 2, "From":"bde", "To":"bk" }'
'{ "DocType": 2, "From":"bde", "To":"mt" }'
'{ "DocType": 2, "From":"mt", "To":"mtr" }'
'{ "DocType": 2, "From":"edn", "To":"mtr" }'
'{ "DocType": 2, "From":"ec", "To":"rm" }'
'{ "DocType": 2, "From":"ec", "To":"srn" }'
'{ "DocType": 2, "From":"srn", "To":"std" }'
'{ "DocType": 2, "From":"gln", "To":"std" }'
'{ "DocType": 2, "From":"gln", "To":"sbk" }'
'{ "DocType": 2, "From":"sbk", "To":"sn" }'
'{ "DocType": 2, "From":"nh", "To":"sn" }'
'{ "DocType": 2, "From":"hb", "To":"nh" }'
'{ "DocType": 2, "From":"hb", "To":"hrl" }'
'{ "DocType": 2, "From":"dv", "To":"dvc" }'
'{ "DocType": 2, "From":"dvc", "To":"hon" }'
'{ "DocType": 2, "From":"hon", "To":"rsn" }'
'{ "DocType": 2, "From":"rsn", "To":"wdn" }'
'{ "DocType": 2, "From":"aml", "To":"wdn" }'
'{ "DocType": 2, "From":"ah", "To":"otb" }'
'{ "DocType": 2, "From":"otb", "To":"wf" }'
'{ "DocType": 2, "From":"ed", "To":"wf" }'
'{ "DocType": 2, "From":"bn", "To":"hgl" }'
'{ "DocType": 2, "From":"amri", "To":"bn" }'
'{ "DocType": 2, "From":"aml", "To":"amri" }'
'{ "DocType": 2, "From":"nvd", "To":"wdn" }'
'{ "DocType": 2, "From":"nvd", "To":"rat" }'
'{ "DocType": 2, "From":"hno", "To":"rat" }'
'{ "DocType": 2, "From":"hno", "To":"zl" }'
'{ "DocType": 2, "From":"apn", "To":"ldl" }'
'{ "DocType": 2, "From":"ldl", "To":"ledn" }'
'{ "DocType": 2, "From":"ut", "To":"vtn" }'
'{ "DocType": 2, "From":"vtn", "To":"wd" }'
'{ "DocType": 2, "From":"bkl", "To":"wd" }'
'{ "DocType": 2, "From":"bdg", "To":"wd" }'
'{ "DocType": 2, "From":"apn", "To":"bdg" }'
'{ "DocType": 2, "From":"akm", "To":"hr" }'
'{ "DocType": 2, "From":"akm", "To":"gw" }'
'{ "DocType": 2, "From":"gw", "To":"lw" }'
'{ "DocType": 2, "From":"mp", "To":"swk" }'
'{ "DocType": 2, "From":"swk", "To":"wv" }'
'{ "DocType": 2, "From":"hr", "To":"wv" }'
'{ "DocType": 2, "From":"gd", "To":"wad" }'
'{ "DocType": 2, "From":"wad", "To":"wadn" }'
'{ "DocType": 2, "From":"bsk", "To":"wadn" }'
'{ "DocType": 2, "From":"apn", "To":"bsk" }'
'{ "DocType": 2, "From":"dl", "To":"zl" }'
'{ "DocType": 2, "From":"dl", "To":"omn" }'
'{ "DocType": 2, "From":"hdb", "To":"omn" }'
'{ "DocType": 2, "From":"co", "To":"gbg" }'
'{ "DocType": 2, "From":"co", "To":"dln" }'
'{ "DocType": 2, "From":"na", "To":"dln" }'
'{ "DocType": 2, "From":"na", "To":"emnb" }'
'{ "DocType": 2, "From":"emn", "To":"emnb" }'
'{ "DocType": 2, "From":"gbg", "To":"hdb" }'
'{ "DocType": 2, "From":"hk", "To":"utg" }'
'{ "DocType": 2, "From":"bv", "To":"hk" }'
'{ "DocType": 2, "From":"bv", "To":"drh" }'
'{ "DocType": 2, "From":"drh", "To":"sptn" }'
'{ "DocType": 2, "From":"sptn", "To":"sptz" }'
'{ "DocType": 2, "From":"bll", "To":"sptz" }'
'{ "DocType": 2, "From":"bll", "To":"hlm" }'
'{ "DocType": 2, "From":"klp", "To":"mrn" }'
'{ "DocType": 2, "From":"aml", "To":"vz" }'
'{ "DocType": 2, "From":"da", "To":"vz" }'
'{ "DocType": 2, "From":"da", "To":"vhp" }'
'{ "DocType": 2, "From":"gdk", "To":"vhp" }'
'{ "DocType": 2, "From":"gdk", "To":"mrb" }'
'{ "DocType": 2, "From":"ktr", "To":"tl" }'
'{ "DocType": 2, "From":"gdm", "To":"tl" }'
'{ "DocType": 2, "From":"ktr", "To":"op" }'
'{ "DocType": 2, "From":"hmn", "To":"op" }'
'{ "DocType": 2, "From":"hmn", "To":"za" }'
'{ "DocType": 2, "From":"est", "To":"za" }'
'{ "DocType": 2, "From":"hgl", "To":"hglo" }'
'{ "DocType": 2, "From":"hglo", "To":"odz" }'
'{ "DocType": 2, "From":"go", "To":"lc" }'
'{ "DocType": 2, "From":"go", "To":"ddn" }'
'{ "DocType": 2, "From":"hgl", "To":"ddn" }'
'{ "DocType": 2, "From":"lc", "To":"zp" }'
'{ "DocType": 2, "From":"mes", "To":"mt" }'
'{ "DocType": 2, "From":"mes", "To":"sgl" }'
'{ "DocType": 2, "From":"sgl", "To":"vk" }'
'{ "DocType": 2, "From":"vk", "To":"sog" }'
'{ "DocType": 2, "From":"sog", "To":"kmr" }'
'{ "DocType": 2, "From":"kmr", "To":"vdl" }'
'{ "DocType": 2, "From":"vdl", "To":"hrl" }'
'{ "DocType": 2, "From":"hrl", "To":"lg" }'
'{ "DocType": 2, "From":"lg", "To":"egh" }'
'{ "DocType": 2, "From":"egh", "To":"cvm" }'
'{ "DocType": 2, "From":"cvm", "To":"krd" }'
'{ "DocType": 2, "From":"tg", "To":"vl" }'
'{ "DocType": 2, "From":"rv", "To":"tg" }'
'{ "DocType": 2, "From":"mrb", "To":"hdb" }'
'{ "DocType": 2, "From":"rv", "To":"sm" }'
'{ "DocType": 2, "From":"rm", "To":"sm" }'
'{ "DocType": 2, "From":"lw", "To":"mg" }'
'{ "DocType": 2, "From":"mg", "To":"sknd" }'
'{ "DocType": 2, "From":"sk", "To":"sknd" }'
'{ "DocType": 2, "From":"ijt", "To":"sk" }'
'{ "DocType": 2, "From":"ijt", "To":"wk" }'
'{ "DocType": 2, "From":"hnp", "To":"wk" }'
'{ "DocType": 2, "From":"hnp", "To":"kmw" }'
'{ "DocType": 2, "From":"kmw", "To":"stv" }'
'{ "DocType": 2, "From":"dei", "To":"lw" }'
'{ "DocType": 2, "From":"dei", "To":"drp" }'
'{ "DocType": 2, "From":"drp", "To":"fn" }'
'{ "DocType": 2, "From":"fn", "To":"hlg" }'
'{ "DocType": 2, "From":"hlg", "To":"hlgh" }'
'{ "DocType": 2, "From":"bp", "To":"zww" }'
'{ "DocType": 2, "From":"zww", "To":"vwd" }'
'{ "DocType": 2, "From":"vwd", "To":"hdg" }'
'{ "DocType": 2, "From":"lw", "To":"hdg" }'
'{ "DocType": 2, "From":"gk", "To":"zh" }'
'{ "DocType": 2, "From":"bp", "To":"gk" }'
'{ "DocType": 2, "From":"gn", "To":"zh" }'
'{ "DocType": 2, "From":"gn", "To":"gnn" }'
'{ "DocType": 2, "From":"gn", "To":"hrn" }'
'{ "DocType": 2, "From":"hrn", "To":"kw" }'
'{ "DocType": 2, "From":"kw", "To":"mth" }'
'{ "DocType": 2, "From":"mth", "To":"hgz" }'
'{ "DocType": 2, "From":"hgz", "To":"spm" }'
'{ "DocType": 2, "From":"spm", "To":"zb" }'
'{ "DocType": 2, "From":"zb", "To":"sda" }'
'{ "DocType": 2, "From":"sda", "To":"ws" }'
'{ "DocType": 2, "From":"ws", "To":"nsch" }'
'{ "DocType": 2, "From":"gnn", "To":"swd" }'
'{ "DocType": 2, "From":"swd", "To":"wsm" }'
'{ "DocType": 2, "From":"bf", "To":"wsm" }'
'{ "DocType": 2, "From":"bf", "To":"wfm" }'
'{ "DocType": 2, "From":"ust", "To":"wfm" }'
'{ "DocType": 2, "From":"uhz", "To":"ust" }'
'{ "DocType": 2, "From":"uhm", "To":"uhz" }'
'{ "DocType": 2, "From":"rd", "To":"uhm" }'
'{ "DocType": 2, "From":"bdm", "To":"swd" }'
'{ "DocType": 2, "From":"bdm", "To":"stm" }'
'{ "DocType": 2, "From":"lp", "To":"stm" }'
'{ "DocType": 2, "From":"apg", "To":"lp" }'
'{ "DocType": 2, "From":"apg", "To":"dzw" }'
'{ "DocType": 2, "From":"dz", "To":"dzw" }'
'{ "DocType": 2, "From":"ht", "To":"zbm" }'
'{ "DocType": 2, "From":"asa", "To":"asdm" }'
'{ "DocType": 2, "From":"asd", "To":"asdm" }'
'{ "DocType": 2, "From":"cl", "To":"htn" }'
'{ "DocType": 2, "From":"cl", "To":"gdm" }'
'{ "DocType": 2, "From":"gdm", "To":"zbm" }'
'{ "DocType": 2, "From":"brn", "To":"hvs" }'
'{ "DocType": 2, "From":"amf", "To":"brn" }'
'{ "DocType": 2, "From":"ot", "To":"tb" }'
'{ "DocType": 2, "From":"btl", "To":"ot" }'
'{ "DocType": 2, "From":"bsd", "To":"ldm" }'
'{ "DocType": 2, "From":"bsd", "To":"gdm" }'
'{ "DocType": 2, "From":"akl", "To":"gr" }'
'{ "DocType": 2, "From":"gr", "To":"gnd" }'
'{ "DocType": 2, "From":"gnd", "To":"sdt" }'
'{ "DocType": 2, "From":"sdt", "To":"ddrs" }'
'{ "DocType": 2, "From":"akl", "To":"ldm" }'
'{ "DocType": 2, "From":"zdk", "To":"zd" }'
'{ "DocType": 2, "From":"zdk", "To":"pmr" }'
'{ "DocType": 2, "From":"pmo", "To":"pmr" }'
'{ "DocType": 2, "From":"htn", "To":"utl" }'
'{ "DocType": 2, "From":"ut", "To":"utl" }'
'{ "DocType": 2, "From":"ddr", "To":"ddrs" }'
'{ "DocType": 2, "From":"gdg", "To":"wd" }'
'{ "DocType": 2, "From":"hor", "To":"uto" }'
'{ "DocType": 2, "From":"hor", "To":"hvsp" }'
)

$viewAllBody = '{
	"language": "javascript",
	"views": {
		"All": {
			"map": "function(doc) {\n\tvar LocationId, Name;\n\tif (doc.DocType == 2) {\n\t\tFrom = doc.From;\n\t\tTo = doc.To;\n\t\temit(From, To);\n\t}\n}"
		}
	}
}'

Function PostConnections2CouchDB($url, $connections)
{
	$connections | foreach {
		$body = $_
		PostConnection2CouchDB $url $body
	}
	Write-Host("Connection documents successful created")
}

Function PostConnection2CouchDB($url, $body)
{
	$return = curl -Uri $url -Method Post -ContentType application/json -Body $body
    if ($return.StatusCode -ne "201")
    {
        Write-Error("Document could not be created, Received $($return.StatusCode) from post for body $body")
    }
}

#
#	beware: this function only works if the view does not exist already (so preferably an empty database)
#		    (reason is the http PUT) 
#
Function PostView2CouchDB($url, $viewBody)
{
	$return = curl -Uri $url -Method Put -ContentType application/javascript -Body $viewBody
    if ($return.StatusCode -ne "201")
    {
		$statusCode = $return.StatusCode
        Write-Error("View All could not be created, Received $statusCode from post for body $viewBody")
    }
    else
    {
        Write-Host("View All successful created")
    }

}
#
#	Script starts here
#
Write-Host("Posting data...")
PostConnections2CouchDB $travelControlUrl $connections

Write-Host("Posting views...")
$viewsUrl = $travelControlUrl + "/_design/Connections"
PostView2CouchDB $viewsUrl $viewAllBody